environment:
  nodejs_version: "6.9.1"
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable

platform:
  - x86
  - x64

cache:
  - node_modules

matrix:
  fast_finish: true

clone_depth: 50

configuration:
  - Release

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run lint
  - npm test

build: false

on_finish:
  - ps: $blockRdp = $true; reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

